services:
  - type: web
    name: monopoly-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r config/requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
